# Generated by Django 4.2.17 on 2024-12-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_schedule',
            name='user',
        ),
        migrations.AddField(
            model_name='teachers_schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schedules', to='store.teachers'),
        ),
    ]
