# Generated by Django 4.2.17 on 2024-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateTimeField(),
        ),
    ]
