# Generated by Django 4.2.17 on 2024-12-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_lesson_lesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='due_data',
        ),
    ]
