# Generated by Django 4.2.17 on 2024-12-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_homework_due_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='rating',
            new_name='stars',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='parent_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='store.coursereview'),
        ),
    ]
