# Generated by Django 4.2.17 on 2024-12-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_rating_coursereview_stars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='teacher',
        ),
    ]
