# Generated by Django 4.2.17 on 2024-12-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_coursereview_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Option_A',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option_B',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option_C',
            field=models.BooleanField(),
        ),
    ]
